// frontend/src/components/modals/ConfigEditorModal.tsx
import {
  Modal,
  Form,
  Select,
  Checkbox,
  InputNumber,
  Button,
  TimePicker,
} from "antd";
import dayjs from "dayjs";
import { useEffect } from "react";

const { Option } = Select;

export interface AutoFunctionConfig {
  id?: string;
  name: string;
  interval_minutes: number;
  start_time?: string;
  end_time?: string;
  enabled: boolean;
}

interface ConfigEditorModalProps {
  open: boolean;
  onClose: () => void;
  config: AutoFunctionConfig | null;
  availableFunctions: Array<{ value: string; label: string }>;
  onSave: (config: AutoFunctionConfig) => void;
}

export function ConfigEditorModal({
  open,
  onClose,
  config,
  availableFunctions,
  onSave,
}: ConfigEditorModalProps) {
  const [form] = Form.useForm();

  useEffect(() => {
    if (open && config) {
      form.setFieldsValue({
        ...config,
        start_time: config.start_time
          ? dayjs(config.start_time, "HH:mm")
          : undefined,
        end_time: config.end_time ? dayjs(config.end_time, "HH:mm") : undefined,
      });
    } else {
      form.resetFields();
    }
  }, [open, config, form]);

  const handleFinish = (values: any) => {
    const newConfig: AutoFunctionConfig = {
      ...config,
      ...values,
      start_time: values.start_time ? values.start_time.format("HH:mm") : null,
      end_time: values.end_time ? values.end_time.format("HH:mm") : null,
    };
    onSave(newConfig);
    onClose();
  };

  return (
    <Modal
      title={config?.id ? `Configure ${config.name}` : "Add New Auto-Function"}
      open={open}
      onCancel={onClose}
      footer={null}
      width={500}
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={handleFinish}
        initialValues={{
          interval_minutes: 60,
          enabled: true,
        }}
      >
        {!config?.id && (
          <Form.Item
            name="name"
            label="Function Name"
            rules={[{ required: true, message: "Please select a function" }]}
          >
            <Select placeholder="Select a function">
              {availableFunctions.map((func) => (
                <Option key={func.value} value={func.value}>
                  {func.label}
                </Option>
              ))}
            </Select>
          </Form.Item>
        )}

        <Form.Item
          name="interval_minutes"
          label="Interval (minutes)"
          rules={[{ required: true, message: "Please enter interval" }]}
        >
          <InputNumber min={1} style={{ width: "100%" }} />
        </Form.Item>

        <div style={{ display: "flex", gap: 16 }}>
          <Form.Item
            name="start_time"
            label="Start Time (Optional)"
            style={{ flex: 1 }}
          >
            <TimePicker format="HH:mm" style={{ width: "100%" }} />
          </Form.Item>
          <Form.Item
            name="end_time"
            label="End Time (Optional)"
            style={{ flex: 1 }}
          >
            <TimePicker format="HH:mm" style={{ width: "100%" }} />
          </Form.Item>
        </div>

        <Form.Item name="enabled" valuePropName="checked">
          <Checkbox>Enable this function</Checkbox>
        </Form.Item>

        <div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}>
          <Button onClick={onClose}>Cancel</Button>
          <Button type="primary" htmlType="submit">
            {config?.id ? "Save" : "Create"}
          </Button>
        </div>
      </Form>
    </Modal>
  );
}

// frontend/src/components/content/SettingsContent/ConfigEditorModal.vue
<template>
  <div v-if="config" class="config-editor">
    <div class="editor-overlay" @click="$emit('close-editor')"></div>
    <div class="editor-modal">
      <h3>
        {{ config.id ? "Configure " + config.name : "Add New Auto-Function" }}
      </h3>

      <!-- Function Name Select -->
      <div v-if="!config.id" class="form-group">
        <label>Function Name:</label>
        <select v-model="config.name" class="form-input form-select">
          <option value="">-- Select a function --</option>
          <option
            v-for="func in availableFunctions"
            :key="func.value"
            :value="func.value"
          >
            {{ func.label }}
          </option>
        </select>
      </div>

      <!-- Interval Input -->
      <div class="form-group">
        <label>Interval (minutes):</label>
        <div class="input-group-number">
          <button
            @click="decrementInterval"
            class="btn-spin"
            type="button"
            aria-label="Decrease interval"
          >
            −
          </button>
          <input
            v-model.number="config.interval_minutes"
            type="number"
            min="1"
            class="form-input"
          />
          <button
            @click="incrementInterval"
            class="btn-spin"
            type="button"
            aria-label="Increase interval"
          >
            +
          </button>
        </div>
      </div>

      <!-- Time Window -->
      <div class="time-window-row">
        <div class="form-group flex-1">
          <label>Start Time (HH:mm) - Optional:</label>
          <div class="time-picker">
            <input
              v-model="config.start_time"
              type="time"
              class="form-input time-input"
            />
            <div class="time-controls">
              <button
                @click="$emit('increment-time', 'start_time', 15)"
                class="btn-time-control"
                title="Add 15 min"
                type="button"
                aria-label="Increase start time by 15 minutes"
              >
                ↑
              </button>
              <button
                @click="$emit('decrement-time', 'start_time', 15)"
                class="btn-time-control"
                title="Sub 15 min"
                type="button"
                aria-label="Decrease start time by 15 minutes"
              >
                ↓
              </button>
            </div>
          </div>
        </div>

        <div class="form-group flex-1">
          <label>End Time (HH:mm) - Optional:</label>
          <div class="time-picker">
            <input
              v-model="config.end_time"
              type="time"
              class="form-input time-input"
            />
            <div class="time-controls">
              <button
                @click="$emit('increment-time', 'end_time', 15)"
                class="btn-time-control"
                title="Add 15 min"
                type="button"
                aria-label="Increase end time by 15 minutes"
              >
                ↑
              </button>
              <button
                @click="$emit('decrement-time', 'end_time', 15)"
                class="btn-time-control"
                title="Sub 15 min"
                type="button"
                aria-label="Decrease end time by 15 minutes"
              >
                ↓
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Enable Checkbox -->
      <div class="form-group">
        <label>
          <input type="checkbox" v-model="config.enabled" class="checkbox" />
          <span class="ml-2">Enable this function</span>
        </label>
      </div>

      <!-- Actions -->
      <div class="editor-actions">
        <button @click="$emit('save-config')" class="btn btn-primary">
          {{ config.id ? "Save" : "Create" }}
        </button>
        <button @click="$emit('close-editor')" class="btn btn-secondary">
          Cancel
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * Config Editor Modal
 * Single Responsibility: Handle configuration form only
 * JSON uses snake_case as per AGENTS.md standard
 */
import { computed } from "vue";
import { type AutoFunctionConfig } from "./configTableUtils";

const props = defineProps<{
  config: AutoFunctionConfig | null;
  availableFunctions: Array<{ value: string; label: string }>;
}>();

defineEmits<{
  "close-editor": [];
  "save-config": [];
  "increment-time": [field: "start_time" | "end_time", minutes: number];
  "decrement-time": [field: "start_time" | "end_time", minutes: number];
}>();

const config = computed(() => props.config);

const incrementInterval = () => {
  if (config.value) {
    config.value.interval_minutes++;
  }
};

const decrementInterval = () => {
  if (config.value) {
    config.value.interval_minutes = Math.max(
      1,
      config.value.interval_minutes - 1,
    );
  }
};
</script>

<style scoped lang="css">
@import "./ScriptMonitor.styles.css";
</style>
