// frontend/src/components/modals/RouteManagementModal.tsx
import {
  Modal,
  Form,
  Input,
  Select,
  Button,
  Checkbox,
  InputNumber,
  Card,
  Row,
  Col,
} from "antd";
import { useEffect } from "react";

const { Option } = Select;

export interface RouteConfig {
  id?: string;
  route_path: string;
  route_method: string;
  category?: string;
  description?: string;
  caching_enabled: boolean;
  cache_ttl?: number;
  cache_strategy?: string;
  queue_enabled: boolean;
  queue_max_size?: number;
  max_concurrent?: number;
  rate_limit_enabled: boolean;
  rate_limit_window?: number;
  rate_limit_max?: number;
}

interface RouteManagementModalProps {
  open: boolean;
  onClose: () => void;
  route: RouteConfig | null;
  onSave: (route: RouteConfig) => void;
}

export function RouteManagementModal({
  open,
  onClose,
  route,
  onSave,
}: RouteManagementModalProps) {
  const [form] = Form.useForm();
  const isEdit = !!route?.id;

  useEffect(() => {
    if (open) {
      if (route) {
        form.setFieldsValue(route);
      } else {
        form.resetFields();
        form.setFieldsValue({
          route_method: "GET",
          caching_enabled: true,
          queue_enabled: true,
          rate_limit_enabled: false,
          cache_ttl: 0,
          cache_strategy: "standard",
          queue_max_size: 100,
          max_concurrent: 5,
          rate_limit_window: 60,
          rate_limit_max: 100,
        });
      }
    }
  }, [open, route, form]);

  const handleFinish = (values: any) => {
    onSave({
      ...route,
      ...values,
    });
    onClose();
  };

  return (
    <Modal
      title={isEdit ? "Edit Route" : "Add New Route"}
      open={open}
      onCancel={onClose}
      footer={null}
      width={700}
    >
      <Form form={form} layout="vertical" onFinish={handleFinish}>
        {/* Basic Info */}
        <Card size="small" style={{ marginBottom: 16 }}>
          <Form.Item
            name="route_path"
            label="Route Path"
            rules={[{ required: true, message: "Please enter route path" }]}
          >
            <Input placeholder="/api/orders" disabled={isEdit} />
          </Form.Item>

          <Row gutter={16}>
            <Col span={12}>
              <Form.Item name="route_method" label="Method">
                <Select>
                  <Option value="GET">GET</Option>
                  <Option value="POST">POST</Option>
                  <Option value="PUT">PUT</Option>
                  <Option value="DELETE">DELETE</Option>
                  <Option value="PATCH">PATCH</Option>
                </Select>
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="category" label="Category">
                <Input placeholder="orders, products, etc" />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item name="description" label="Description">
            <Input placeholder="Route description" />
          </Form.Item>
        </Card>

        {/* Caching */}
        <Card
          size="small"
          title={
            <Form.Item name="caching_enabled" valuePropName="checked" noStyle>
              <Checkbox>Enable Caching</Checkbox>
            </Form.Item>
          }
          style={{ marginBottom: 16 }}
        >
          <Form.Item
            noStyle
            shouldUpdate={(prev, curr) =>
              prev.caching_enabled !== curr.caching_enabled
            }
          >
            {({ getFieldValue }) =>
              getFieldValue("caching_enabled") && (
                <Row gutter={16}>
                  <Col span={12}>
                    <Form.Item label="TTL (seconds)" name="cache_ttl">
                      <InputNumber
                        min={0}
                        max={3600}
                        style={{ width: "100%" }}
                      />
                    </Form.Item>
                  </Col>
                  <Col span={12}>
                    <Form.Item label="Strategy" name="cache_strategy">
                      <Select>
                        <Option value="standard">Standard</Option>
                        <Option value="aggressive">Aggressive</Option>
                        <Option value="minimal">Minimal</Option>
                      </Select>
                    </Form.Item>
                  </Col>
                </Row>
              )
            }
          </Form.Item>
        </Card>

        {/* Queue */}
        <Card
          size="small"
          title={
            <Form.Item name="queue_enabled" valuePropName="checked" noStyle>
              <Checkbox>Enable Queue</Checkbox>
            </Form.Item>
          }
          style={{ marginBottom: 16 }}
        >
          <Form.Item
            noStyle
            shouldUpdate={(prev, curr) =>
              prev.queue_enabled !== curr.queue_enabled
            }
          >
            {({ getFieldValue }) =>
              getFieldValue("queue_enabled") && (
                <Row gutter={16}>
                  <Col span={12}>
                    <Form.Item label="Max Size" name="queue_max_size">
                      <InputNumber
                        min={1}
                        max={1000}
                        style={{ width: "100%" }}
                      />
                    </Form.Item>
                  </Col>
                  <Col span={12}>
                    <Form.Item label="Max Concurrent" name="max_concurrent">
                      <InputNumber min={1} max={50} style={{ width: "100%" }} />
                    </Form.Item>
                  </Col>
                </Row>
              )
            }
          </Form.Item>
        </Card>

        {/* Rate Limit */}
        <Card
          size="small"
          title={
            <Form.Item
              name="rate_limit_enabled"
              valuePropName="checked"
              noStyle
            >
              <Checkbox>Enable Rate Limiting</Checkbox>
            </Form.Item>
          }
          style={{ marginBottom: 16 }}
        >
          <Form.Item
            noStyle
            shouldUpdate={(prev, curr) =>
              prev.rate_limit_enabled !== curr.rate_limit_enabled
            }
          >
            {({ getFieldValue }) =>
              getFieldValue("rate_limit_enabled") && (
                <Row gutter={16}>
                  <Col span={12}>
                    <Form.Item label="Window (sec)" name="rate_limit_window">
                      <InputNumber
                        min={1}
                        max={3600}
                        style={{ width: "100%" }}
                      />
                    </Form.Item>
                  </Col>
                  <Col span={12}>
                    <Form.Item label="Max Requests" name="rate_limit_max">
                      <InputNumber
                        min={1}
                        max={10000}
                        style={{ width: "100%" }}
                      />
                    </Form.Item>
                  </Col>
                </Row>
              )
            }
          </Form.Item>
        </Card>

        <div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}>
          <Button onClick={onClose}>Cancel</Button>
          <Button type="primary" htmlType="submit">
            {isEdit ? "Update" : "Create"}
          </Button>
        </div>
      </Form>
    </Modal>
  );
}

// frontend/src/components/content/SettingsContent/RouteManagementModal.vue
<template>
  <div class="modal-overlay">
    <div class="modal-content modal-large">
      <div class="modal-header">
        <h4>{{ route?.id ? "Edit Route" : "Add New Route" }}</h4>
        <button
          @click="$emit('close')"
          class="btn-close"
          type="button"
          aria-label="Close modal"
        >
          ✕
        </button>
      </div>

      <form @submit.prevent="saveForm">
        <!-- Basic Info Section -->
        <div class="form-section">
          <div class="form-group">
            <label>Route Path *</label>
            <input
              v-model="formData.route_path"
              type="text"
              placeholder="/api/orders"
              class="form-input"
              :readonly="!!route?.id"
            />
          </div>
          <div class="form-row">
            <div class="form-group">
              <label>Method</label>
              <select v-model="formData.route_method" class="form-select">
                <option>GET</option>
                <option>POST</option>
                <option>PUT</option>
                <option>DELETE</option>
                <option>PATCH</option>
              </select>
            </div>
            <div class="form-group">
              <label>Category</label>
              <input
                v-model="formData.category"
                type="text"
                placeholder="orders, products, etc"
                class="form-input"
              />
            </div>
          </div>
          <div class="form-group">
            <label>Description</label>
            <input
              v-model="formData.description"
              type="text"
              placeholder="Route description"
              class="form-input"
            />
          </div>
        </div>

        <!-- Caching Section -->
        <div class="form-section">
          <h5>⚙️ Caching</h5>
          <label
            ><input v-model="formData.caching_enabled" type="checkbox" />
            Enable</label
          >
          <div v-if="formData.caching_enabled" class="form-row">
            <div class="form-group">
              <label>TTL (seconds)</label>
              <input
                v-model.number="formData.cache_ttl"
                type="number"
                min="0"
                max="3600"
                class="form-input"
              />
            </div>
            <div class="form-group">
              <label>Strategy</label>
              <select v-model="formData.cache_strategy" class="form-select">
                <option value="standard">Standard</option>
                <option value="aggressive">Aggressive</option>
                <option value="minimal">Minimal</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Queue Section -->
        <div class="form-section">
          <h5>📋 Queue</h5>
          <label
            ><input v-model="formData.queue_enabled" type="checkbox" />
            Enable</label
          >
          <div v-if="formData.queue_enabled" class="form-row">
            <div class="form-group">
              <label>Max Size</label>
              <input
                v-model.number="formData.queue_max_size"
                type="number"
                min="1"
                max="1000"
                class="form-input"
              />
            </div>
            <div class="form-group">
              <label>Max Concurrent</label>
              <input
                v-model.number="formData.max_concurrent"
                type="number"
                min="1"
                max="50"
                class="form-input"
              />
            </div>
          </div>
        </div>

        <!-- Rate Limit Section -->
        <div class="form-section">
          <h5>⏱️ Rate Limit</h5>
          <label
            ><input v-model="formData.rate_limit_enabled" type="checkbox" />
            Enable</label
          >
          <div v-if="formData.rate_limit_enabled" class="form-row">
            <div class="form-group">
              <label>Window (sec)</label>
              <input
                v-model.number="formData.rate_limit_window"
                type="number"
                min="1"
                max="3600"
                class="form-input"
              />
            </div>
            <div class="form-group">
              <label>Max Requests</label>
              <input
                v-model.number="formData.rate_limit_max"
                type="number"
                min="1"
                max="10000"
                class="form-input"
              />
            </div>
          </div>
        </div>

        <!-- Form Actions -->
        <div class="modal-footer">
          <button
            type="button"
            @click="$emit('close')"
            class="btn btn-secondary"
          >
            Cancel
          </button>
          <button type="submit" class="btn btn-primary" :disabled="isSaving">
            {{ isSaving ? "Saving..." : "💾 Save" }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive } from "vue";
import type { RouteConfig } from "./types/routeManagement";

interface Props {
  route: RouteConfig | null;
  isSaving: boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  save: [route: RouteConfig];
  close: [];
}>();

const formData = reactive<RouteConfig>(
  props.route || {
    route_path: "",
    route_method: "GET",
    enabled: true,
    caching_enabled: true,
    cache_ttl: 0,
    cache_strategy: "standard",
    queue_enabled: true,
    queue_max_size: 100,
    queue_priority: "normal",
    max_concurrent: 5,
    rate_limit_enabled: false,
    rate_limit_window: 60,
    rate_limit_max: 100,
    min_interval_ms: 0,
    timeout: 30000,
    retry_enabled: true,
    max_retries: 3,
    retry_delay_ms: 1000,
  },
);

const saveForm = () => {
  emit("save", formData);
};
</script>

<style src="./RouteManagementModal.styles.css" scoped></style>
