// frontend/src/components/analytics/TiktokPriceResultsTable.vue
<template>
  <div class="results-section">
    <div class="section-header">
      <h2>📋 TikTok SKU Price Analysis</h2>
      <span class="result-count">{{ skuGroups.length }} items</span>
    </div>
    <div class="table-container">
      <table class="results-table">
        <thead>
          <tr>
            <th class="col-status">Status</th>
            <th class="col-sku">SKU</th>
            <th class="col-name">Item Name</th>
            <th class="col-price">Marketplace Price</th>
            <th class="col-price">Inventory Price</th>
            <th class="col-price">Actual Income</th>
            <th class="col-price">Expected Income</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="sku in skuGroups"
            :key="sku.sku"
            :class="getRowClass(sku.status)"
          >
            <td>
              <span :class="['status-badge', sku.status.toLowerCase()]">
                {{ getStatusLabel(sku.status) }}
              </span>
            </td>
            <td class="cell-sku">{{ sku.seller_sku || sku.sku }}</td>
            <td class="cell-name">
              {{ sku.product_name }}
              <span v-if="sku.variant_name" class="variant-name">
                - {{ sku.variant_name }}
              </span>
            </td>
            <td class="cell-price">
              <span v-for="(price, idx) in sku.unique_unit_prices" :key="idx">
                {{ formatPrice(price)
                }}<span v-if="idx < sku.unique_unit_prices.length - 1">, </span>
              </span>
            </td>
            <td class="cell-price">{{ formatPrice(sku.inventory_price) }}</td>
            <td class="cell-price">
              <span
                v-for="(income, idx) in getTopTwoSmallestIncomes(
                  sku.unique_actual_incomes,
                )"
                :key="idx"
              >
                {{ formatPrice(income)
                }}<span
                  v-if="
                    idx <
                    getTopTwoSmallestIncomes(sku.unique_actual_incomes).length -
                      1
                  "
                  >,
                </span>
              </span>
            </td>
            <td class="cell-price expected">
              {{ formatPrice(sku.expected_income) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
interface SkuGroup {
  sku: string;
  seller_sku: string;
  product_name: string;
  variant_name?: string;
  status: string;
  inventory_price: number | null;
  unique_unit_prices: number[];
  unique_actual_incomes: number[];
  expected_income: number | null;
  total_transactions: number;
}

defineProps<{ skuGroups: SkuGroup[] }>();

function getStatusLabel(status: string): string {
  switch (status) {
    case "OK":
      return "✓ OK";
    case "PRICE_DIFF":
      return "⚠ Diff";
    case "NO_INVENTORY":
      return "? N/A";
    default:
      return status;
  }
}

function getRowClass(status: string): string {
  switch (status) {
    case "OK":
      return "row-ok";
    case "PRICE_DIFF":
      return "row-warning";
    case "NO_INVENTORY":
      return "row-info";
    default:
      return "";
  }
}

function formatPrice(price: number | null): string {
  if (price === null || price === undefined) return "-";
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
}

function getTopTwoSmallestIncomes(incomes: number[]): number[] {
  if (!incomes || incomes.length === 0) return [];
  const sorted = [...incomes].sort((a, b) => a - b);
  return sorted.slice(0, 2);
}
</script>

<style scoped>
.results-section {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  overflow: hidden;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  border-bottom: 2px solid #e0e0e0;
  background: #f5f5f5;
}

.section-header h2 {
  margin: 0;
  font-size: 1.1rem;
  color: #2c3e50;
}

.result-count {
  font-size: 0.9rem;
  color: #6b7280;
}

.table-container {
  overflow-x: auto;
}

.results-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
}

.results-table th {
  padding: 12px 15px;
  text-align: left;
  background: #f5f5f5;
  color: #2c3e50;
  font-weight: 600;
  position: sticky;
  top: 0;
  font-size: 0.85rem;
  text-transform: uppercase;
}

.results-table td {
  padding: 12px 15px;
  border-bottom: 1px solid #f0f0f0;
}

.results-table tbody tr:hover {
  background: rgba(99, 102, 241, 0.05);
}

.row-ok {
  background: rgba(34, 197, 94, 0.03);
}
.row-warning {
  background: rgba(245, 158, 11, 0.05);
}
.row-info {
  background: rgba(59, 130, 246, 0.03);
}

.status-badge {
  padding: 6px 10px;
  border-radius: 4px;
  font-size: 0.8rem;
  font-weight: 500;
}

.status-badge.ok {
  background: #dcfce7;
  color: #166534;
}

.status-badge.price_diff {
  background: #fef3c7;
  color: #92400e;
}

.status-badge.no_inventory {
  background: #dbeafe;
  color: #1e40af;
}

.cell-sku {
  font-family: "Consolas", monospace;
  font-size: 0.9rem;
  color: #1976d2;
  text-align: left;
  font-weight: 600;
}

.cell-name {
  color: var(--color-text-secondary);
  text-align: left;
  word-wrap: break-word;
  white-space: normal;
  line-height: 1.4;
  min-width: 200px;
  max-width: 300px;
}

.variant-name {
  color: var(--color-text-muted);
  font-style: italic;
}

.cell-price {
  font-family: "Consolas", monospace;
  text-align: left;
  color: var(--color-text-secondary);
}

.cell-price.expected {
  color: var(--color-success);
  font-weight: 600;
}

@media (max-width: 768px) {
  .results-table {
    font-size: 0.75rem;
  }
}
</style>

// frontend/src/pages/analytics/components/tiktok/TiktokPriceResultsTable.tsx
import { Table, Tag, Typography, Tooltip, theme } from "antd";
import type { ColumnsType } from "antd/es/table";
import {
  CheckCircleOutlined,
  WarningOutlined,
  QuestionCircleOutlined,
} from "@ant-design/icons";
import type { TiktokSkuGroup } from "@/types/analytics";
import { formatCurrency } from "@/lib/analyticsHelpers";

const { Text } = Typography;

interface Props {
  skuGroups: TiktokSkuGroup[];
  loading?: boolean;
}

export function TiktokPriceResultsTable({ skuGroups, loading }: Props) {
  const { token } = theme.useToken();

  const getStatusColor = (status: string) => {
    switch (status) {
      case "OK":
        return "success";
      case "PRICE_DIFF":
        return "warning";
      case "NO_INVENTORY":
        return "default";
      default:
        return "default";
    }
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "OK":
        return (
          <span>
            <CheckCircleOutlined /> OK
          </span>
        );
      case "PRICE_DIFF":
        return (
          <span>
            <WarningOutlined /> Diff
          </span>
        );
      case "NO_INVENTORY":
        return (
          <span>
            <QuestionCircleOutlined /> N/A
          </span>
        );
      default:
        return status;
    }
  };

  const getTopTwoSmallestIncomes = (incomes: number[]): number[] => {
    if (!incomes || incomes.length === 0) return [];
    const sorted = [...incomes].sort((a, b) => a - b);
    return sorted.slice(0, 2);
  };

  const columns: ColumnsType<TiktokSkuGroup> = [
    {
      title: "Status",
      dataIndex: "status",
      key: "status",
      width: 100,
      fixed: "left",
      render: (status: string) => (
        <Tag
          color={getStatusColor(status)}
          style={{ minWidth: 60, textAlign: "center" }}
        >
          {getStatusLabel(status)}
        </Tag>
      ),
      filters: [
        { text: "OK", value: "OK" },
        { text: "Diff", value: "PRICE_DIFF" },
        { text: "N/A", value: "NO_INVENTORY" },
      ],
      onFilter: (value, record) => record.status === value,
    },
    {
      title: "SKU",
      dataIndex: "sku", // Using sku as primary identifier, though Vue uses model_sku or sku
      key: "sku",
      width: 150,
      fixed: "left",
      render: (sku: string, record) => (
        <Tooltip
          title={
            record.seller_sku !== sku
              ? `Seller SKU: ${record.seller_sku}`
              : null
          }
        >
          <Text
            style={{
              fontFamily: "monospace",
              color: token.colorPrimary,
              fontWeight: 600,
            }}
          >
            {sku}
          </Text>
        </Tooltip>
      ),
      sorter: (a, b) => a.sku.localeCompare(b.sku),
    },
    {
      title: "Item Name",
      dataIndex: "product_name",
      key: "item_name",
      width: 300,
      render: (name: string) => (
        <Text
          style={{
            whiteSpace: "normal",
            wordWrap: "break-word",
            lineHeight: 1.4,
          }}
        >
          {name}
        </Text>
      ),
      sorter: (a, b) => a.product_name.localeCompare(b.product_name),
    },
    {
      title: "Marketplace Price",
      dataIndex: "unique_unit_prices",
      key: "marketplace_price",
      width: 150,
      render: (prices: number[]) => (
        <Text code>{prices.map((p) => formatCurrency(p)).join(", ")}</Text>
      ),
    },
    {
      title: "Inventory Price",
      dataIndex: "inventory_price",
      key: "inventory_price",
      width: 140,
      align: "right",
      render: (price: number | null) => (
        <Text code>{price !== null ? formatCurrency(price) : "-"}</Text>
      ),
      sorter: (a, b) => (a.inventory_price || 0) - (b.inventory_price || 0),
    },
    {
      title: "Actual Income",
      dataIndex: "unique_actual_incomes",
      key: "actual_income",
      width: 160,
      align: "right",
      render: (incomes: number[]) => {
        const topTwo = getTopTwoSmallestIncomes(incomes);
        return (
          <Text code>
            {topTwo.map((p) => formatCurrency(p)).join(", ")}
            {incomes.length > 2 && "..."}
          </Text>
        );
      },
    },
    {
      title: "Expected Income",
      dataIndex: "expected_income",
      key: "expected_income",
      width: 140,
      align: "right",
      render: (price: number | null) => (
        <Text
          style={{
            color: token.colorSuccess,
            fontWeight: 600,
            fontFamily: "monospace",
          }}
        >
          {price !== null ? formatCurrency(price) : "-"}
        </Text>
      ),
      sorter: (a, b) => (a.expected_income || 0) - (b.expected_income || 0),
    },
  ];

  return (
    <div
      style={{
        background: token.colorBgContainer,
        borderRadius: token.borderRadiusLG,
        padding: 0,
        overflow: "hidden",
        border: `1px solid ${token.colorBorderSecondary}`,
      }}
    >
      <div
        style={{
          padding: "16px 20px",
          borderBottom: `2px solid ${token.colorBorderSecondary}`,
          background: token.colorFillAlter,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <Typography.Title
          level={4}
          style={{
            margin: 0,
            fontSize: "1.1rem",
            color: token.colorTextHeading,
          }}
        >
          📋 TikTok SKU Price Analysis
        </Typography.Title>
        <Text type="secondary" style={{ fontSize: "0.9rem" }}>
          {skuGroups.length} items
        </Text>
      </div>
      <Table
        columns={columns}
        dataSource={skuGroups}
        rowKey="sku"
        loading={loading}
        pagination={{
          pageSize: 10,
          showSizeChanger: true,
          showTotal: (total) => `Total ${total} items`,
          position: ["bottomRight"],
        }}
        scroll={{ x: 1200 }}
        size="small"
        rowClassName={(record) => {
          switch (record.status) {
            case "OK":
              return "table-row-ok";
            case "PRICE_DIFF":
              return "table-row-warning";
            case "NO_INVENTORY":
              return "table-row-info";
            default:
              return "";
          }
        }}
        style={{ fontSize: "0.9rem" }}
      />
      <style>
        {`
          .table-row-ok { background-color: rgba(34, 197, 94, 0.03); }
          .table-row-warning { background-color: rgba(245, 158, 11, 0.05); }
          .table-row-info { background-color: rgba(59, 130, 246, 0.03); }
        `}
      </style>
    </div>
  );
}

export default TiktokPriceResultsTable;
