// frontend/src/components/analytics/TiktokShippingFeeTable.vue
<template>
  <div class="results-section">
    <div class="section-header">
      <h2>🚚 TikTok Shipping Fee Analysis</h2>
      <span class="result-count"
        >{{ orders.length }} orders with difference</span
      >
    </div>
    <div class="table-container">
      <table class="results-table">
        <thead>
          <tr>
            <th class="col-date">Order Date</th>
            <th class="col-order">Order ID</th>
            <th class="col-price">Original Fee</th>
            <th class="col-price">Buyer Paid</th>
            <th class="col-price">Platform Discount</th>
            <th class="col-price">Seller Pays</th>
            <th class="col-status">Status</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="order in orders" :key="order.order_id" class="row-loss">
            <td class="cell-date">{{ order.order_date || "-" }}</td>
            <td class="cell-order">{{ order.order_id }}</td>
            <td class="cell-price">{{ formatPrice(order.original_fee) }}</td>
            <td class="cell-price">{{ formatPrice(order.buyer_paid) }}</td>
            <td class="cell-price">
              {{ formatPrice(order.platform_discount) }}
            </td>
            <td class="cell-price value-loss">
              -{{ formatPrice(order.seller_pays) }}
            </td>
            <td class="cell-status">{{ order.order_status || "-" }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
interface TiktokShippingFeeOrder {
  order_id: string;
  order_date: string | null;
  original_fee: number;
  buyer_paid: number;
  platform_discount: number;
  seller_pays: number;
  order_status: string | null;
  currency: string;
}

defineProps<{ orders: TiktokShippingFeeOrder[] }>();

function formatPrice(price: number | null): string {
  if (price === null || price === undefined) return "-";
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
}
</script>

<style scoped>
.results-section {
  background: var(--color-surface);
  border-radius: var(--radius-lg);
  border: 1px solid var(--color-border);
  overflow: hidden;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--space-md) var(--space-lg);
  border-bottom: 1px solid var(--color-border);
  background: var(--color-surface-alt);
}

.section-header h2 {
  margin: 0;
  font-size: 1rem;
  color: var(--color-text-primary);
}

.result-count {
  font-size: 0.85rem;
  color: var(--color-text-muted);
}

.table-container {
  overflow-x: auto;
}

.results-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.85rem;
}

.results-table th,
.results-table td {
  padding: var(--space-sm) var(--space-md);
  text-align: left;
  border-bottom: 1px solid var(--color-border);
}

.results-table th {
  background: var(--color-surface-alt);
  font-weight: 600;
  color: var(--color-text-secondary);
  white-space: nowrap;
}

.col-date {
  width: 100px;
}
.col-order {
  width: 180px;
}
.col-price {
  width: 110px;
  text-align: right;
}
.col-status {
  width: 100px;
}

.cell-date {
  color: var(--color-text-muted);
}
.cell-order {
  font-family: monospace;
  font-size: 0.8rem;
}
.cell-price {
  text-align: right;
}
.cell-status {
  color: var(--color-text-secondary);
}

.row-profit {
  background: var(--color-success-bg, rgba(34, 197, 94, 0.05));
}

.row-loss {
  background: var(--color-error-bg, rgba(239, 68, 68, 0.05));
}

.value-profit {
  color: var(--color-success, #22c55e);
  font-weight: 600;
}

.value-loss {
  color: var(--color-error, #ef4444);
  font-weight: 600;
}
</style>

// frontend/src/pages/analytics/components/tiktok/TiktokShippingFeeTable.tsx
import { Table, Typography, Tag, theme } from "antd";
import type { ColumnsType } from "antd/es/table";
import type { TiktokShippingFeeOrder } from "@/types/analytics";
import { formatCurrency, formatAnalyticsDate } from "@/lib/analyticsHelpers";

const { Text } = Typography;

interface Props {
  orders: TiktokShippingFeeOrder[];
  loading?: boolean;
}

export function TiktokShippingFeeTable({ orders, loading }: Props) {
  const { token } = theme.useToken();

  const columns: ColumnsType<TiktokShippingFeeOrder> = [
    {
      title: "Order Date",
      dataIndex: "order_date",
      key: "order_date",
      width: 120,
      fixed: "left",
      render: (date: string | null) => (
        <Text type="secondary">{formatAnalyticsDate(date)}</Text>
      ),
      sorter: (a, b) => {
        if (!a.order_date) return -1;
        if (!b.order_date) return 1;
        return (
          new Date(a.order_date).getTime() - new Date(b.order_date).getTime()
        );
      },
    },
    {
      title: "Order ID",
      dataIndex: "order_id",
      key: "order_id",
      width: 180,
      fixed: "left",
      render: (id: string) => (
        <Text
          copyable={{ text: id }}
          style={{ fontFamily: "monospace", fontSize: "0.85rem" }}
        >
          {id}
        </Text>
      ),
    },
    {
      title: "Buyer Paid",
      dataIndex: "buyer_paid",
      key: "buyer_paid",
      width: 130,
      align: "right",
      render: (val: number) => <Text>{formatCurrency(val)}</Text>,
      sorter: (a, b) => a.buyer_paid - b.buyer_paid,
    },
    {
      title: "Actual Fee",
      dataIndex: "actual_fee",
      key: "actual_fee",
      width: 130,
      align: "right",
      render: (val: number) => <Text>{formatCurrency(val)}</Text>,
      sorter: (a, b) => a.actual_fee - b.actual_fee,
    },
    {
      title: "Platform Discount",
      dataIndex: "platform_discount",
      key: "platform_discount",
      width: 150,
      align: "right",
      render: (val: number) => <Text>{formatCurrency(val)}</Text>,
    },
    {
      title: "Difference",
      dataIndex: "difference",
      key: "difference",
      width: 130,
      align: "right",
      render: (val: number) => (
        <Text
          style={{
            color: val >= 0 ? token.colorSuccess : token.colorError,
            fontWeight: 600,
          }}
        >
          {val > 0 ? "+" : ""}
          {formatCurrency(val)}
        </Text>
      ),
      sorter: (a, b) => a.difference - b.difference,
    },
    {
      title: "Status",
      dataIndex: "order_status",
      key: "order_status",
      width: 140,
      render: (status: string) => <Tag>{status}</Tag>,
      filters: Array.from(new Set(orders.map((o) => o.order_status))).map(
        (s) => ({ text: s, value: s || "" }),
      ),
      onFilter: (value, record) => record.order_status === value,
    },
  ];

  return (
    <div
      style={{
        background: token.colorBgContainer,
        borderRadius: token.borderRadiusLG,
        padding: 0,
        overflow: "hidden",
        border: `1px solid ${token.colorBorderSecondary}`,
      }}
    >
      <div
        style={{
          padding: "16px 20px",
          borderBottom: `2px solid ${token.colorBorderSecondary}`,
          background: token.colorFillAlter,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <Typography.Title
          level={4}
          style={{
            margin: 0,
            fontSize: "1.1rem",
            color: token.colorTextHeading,
          }}
        >
          🚚 TikTok Shipping Fee Analysis
        </Typography.Title>
        <Text type="secondary" style={{ fontSize: "0.9rem" }}>
          {orders.length} orders with difference
        </Text>
      </div>
      <Table
        columns={columns}
        dataSource={orders}
        rowKey="order_id"
        loading={loading}
        pagination={{
          pageSize: 10,
          showSizeChanger: true,
          showTotal: (total) => `Total ${total} items`,
          position: ["bottomRight"],
        }}
        scroll={{ x: 1000 }}
        size="small"
        rowClassName={(record) =>
          record.difference < 0
            ? "table-row-loss"
            : record.difference > 0
              ? "table-row-profit"
              : ""
        }
        style={{ fontSize: "0.85rem" }}
      />
      <style>
        {`
          .table-row-profit { background-color: rgba(34, 197, 94, 0.05); }
          .table-row-loss { background-color: rgba(239, 68, 68, 0.05); }
        `}
      </style>
    </div>
  );
}

export default TiktokShippingFeeTable;
