// frontend/src/components/analytics/AdsTrendChart.vue
<template>
  <div class="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
    <div class="flex justify-between items-center mb-4">
      <h3 class="text-lg font-semibold text-gray-700">Performance Trend</h3>
      <!-- Simple Toggle for Metrics could go here -->
    </div>
    <div
      v-if="loading"
      class="h-80 flex items-center justify-center bg-gray-50 rounded"
    >
      <span class="text-gray-400">Loading chart...</span>
    </div>
    <div
      v-else-if="series.length === 0"
      class="h-80 flex items-center justify-center bg-gray-50 rounded"
    >
      <span class="text-gray-400">No data available for this period</span>
    </div>
    <div v-else>
      <apexchart
        width="100%"
        height="350"
        type="line"
        :options="chartOptions"
        :series="series"
      ></apexchart>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, defineProps } from "vue";
import type { TrendDataPoint } from "../../stores/analytics";

const props = defineProps<{
  data: TrendDataPoint[];
  loading: boolean;
}>();

const series = computed(() => {
  if (!props.data || props.data.length === 0) return [];

  return [
    {
      name: "GMV (Omzet)",
      type: "column",
      data: props.data.map((d) => d.gmv),
    },
    {
      name: "Ad Spend (Biaya)",
      type: "line",
      data: props.data.map((d) => d.spend),
    },
  ];
});

const chartOptions = computed(() => ({
  chart: {
    height: 350,
    type: "line",
    toolbar: { show: false },
    zoom: { enabled: false },
  },
  stroke: {
    width: [0, 3],
    curve: "smooth",
  },
  plotOptions: {
    bar: {
      columnWidth: "50%",
      borderRadius: 4,
    },
  },
  dataLabels: {
    enabled: false,
  },
  labels: props.data.map((d) => d.label || d.period_start), // X-axis labels
  xaxis: {
    type: "category", // or 'datetime' if we parse dates
    tooltip: {
      enabled: false,
    },
  },
  yaxis: [
    {
      title: {
        text: "GMV (IDR)",
      },
      labels: {
        formatter: (val: number) => {
          if (val >= 1000000) return (val / 1000000).toFixed(1) + "M";
          if (val >= 1000) return (val / 1000).toFixed(0) + "k";
          return val;
        },
      },
    },
    {
      opposite: true,
      title: {
        text: "Ad Spend (IDR)",
      },
      labels: {
        formatter: (val: number) => {
          if (val >= 1000000) return (val / 1000000).toFixed(1) + "M";
          if (val >= 1000) return (val / 1000).toFixed(0) + "k";
          return val;
        },
      },
    },
  ],
  colors: ["#3B82F6", "#EF4444"], // Blue for Sales, Red for Cost
  tooltip: {
    shared: true,
    intersect: false,
    y: {
      formatter: (y: number) => {
        if (typeof y !== "undefined") {
          return new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            maximumFractionDigits: 0,
          }).format(y);
        }
        return y;
      },
    },
  },
  legend: {
    position: "top",
    horizontalAlign: "right",
  },
}));
</script>

// frontend/src/components/analytics/ads/AdsTrendChart.tsx
import { useMemo } from "react";
import ReactApexChart from "react-apexcharts";
import { Spin, theme } from "antd";
import type { ApexOptions } from "apexcharts";
import type { FC } from "react";

interface TrendDataPoint {
  label: string;
  spend: number;
  gmv: number;
}

interface AdsTrendChartProps {
  data: TrendDataPoint[];
  loading?: boolean;
}

export const AdsTrendChart: FC<AdsTrendChartProps> = ({ data, loading }) => {
  const { token } = theme.useToken();

  const series = useMemo(() => {
    if (!data || data.length === 0) return [];
    return [
      {
        name: "GMV (Omzet)",
        type: "column",
        data: data.map((d) => d.gmv),
      },
      {
        name: "Ad Spend (Biaya)",
        type: "line",
        data: data.map((d) => d.spend),
      },
    ];
  }, [data]);

  const options: ApexOptions = useMemo(
    () => ({
      chart: {
        height: 350,
        type: "line",
        toolbar: { show: false },
        zoom: { enabled: false },
      },
      stroke: {
        width: [0, 3],
        curve: "smooth",
      },
      plotOptions: {
        bar: {
          columnWidth: "50%",
          borderRadius: 4,
        },
      },
      dataLabels: {
        enabled: false,
      },
      labels: data.map((d) => d.label),
      xaxis: {
        type: "category",
        tooltip: {
          enabled: false,
        },
      },
      yaxis: [
        {
          title: {
            text: "GMV (IDR)",
          },
          labels: {
            formatter: (val: number) => {
              if (val >= 1000000) return `${(val / 1000000).toFixed(1)}M`;
              if (val >= 1000) return `${(val / 1000).toFixed(0)}k`;
              return String(val);
            },
          },
        },
        {
          opposite: true,
          title: {
            text: "Ad Spend (IDR)",
          },
          labels: {
            formatter: (val: number) => {
              if (val >= 1000000) return `${(val / 1000000).toFixed(1)}M`;
              if (val >= 1000) return `${(val / 1000).toFixed(0)}k`;
              return String(val);
            },
          },
        },
      ],
      colors: [token.colorPrimary, token.colorError],
      tooltip: {
        shared: true,
        intersect: false,
        y: {
          formatter: (y: number) => {
            if (typeof y !== "undefined") {
              return new Intl.NumberFormat("id-ID", {
                style: "currency",
                currency: "IDR",
                maximumFractionDigits: 0,
              }).format(y);
            }
            return "";
          },
        },
      },
      legend: {
        position: "top",
        horizontalAlign: "right",
      },
    }),
    [data, token.colorPrimary, token.colorError],
  );

  if (loading) {
    return (
      <div
        style={{
          height: 350,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          background: token.colorFillAlter,
          borderRadius: token.borderRadius,
        }}
      >
        <Spin />
      </div>
    );
  }

  if (!data || data.length === 0) {
    return (
      <div
        style={{
          height: 350,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          background: token.colorFillAlter,
          borderRadius: token.borderRadius,
        }}
      >
        <span style={{ color: token.colorTextSecondary }}>
          No data available for this period
        </span>
      </div>
    );
  }

  return (
    <ReactApexChart
      options={options}
      series={series}
      type="line"
      height={350}
    />
  );
};

export default AdsTrendChart;
