// frontend/src/components/content/InventoryContent/tabs/MpqTab.vue
<template>
  <div class="tab-content">
    <!-- Platform Support Info -->
    <div class="info-banner">
      <span class="info-icon">📦</span>
      <div class="info-text">
        <strong>MPQ (Min Purchase Quantity)</strong>
        <p class="info-note">
          Shopee: min_purchase_limit + delete wholesale | TikTok:
          minimum_order_quantity
        </p>
      </div>
    </div>

    <!-- Tier Selector -->
    <div class="tier-selector">
      <label>Pilih Tier:</label>
      <div class="tier-options">
        <button
          v-for="tier in tiers"
          :key="tier.value"
          :class="['tier-btn', { active: selectedTier === tier.value }]"
          @click="selectedTier = tier.value"
        >
          {{ tier.label }}
          <span class="tier-qty">Min: {{ tier.minQty }}</span>
        </button>
      </div>
    </div>

    <!-- Preview Section -->
    <div
      class="preview-section"
      v-if="shopeeItems.length + tiktokItems.length > 0"
    >
      <!-- Shopee Preview -->
      <div v-if="shopeeItems.length > 0" class="platform-preview">
        <h3 class="platform-title">
          <span class="platform-badge shopee">Shopee</span>
          {{ shopeeItems.length }} item
        </h3>
        <table class="preview-table" aria-label="Shopee MPQ preview">
          <thead>
            <tr>
              <th scope="col">SKU</th>
              <th scope="col">Harga Awal</th>
              <th scope="col">Harga Baru</th>
              <th scope="col">MPQ</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in shopeePreview" :key="item.sku">
              <td class="sku-cell">{{ item.sku }}</td>
              <td>{{ formatPrice(item.price) }}</td>
              <td class="price-cell">{{ formatPrice(item.newPrice) }}</td>
              <td>{{ selectedMinQty }}</td>
            </tr>
          </tbody>
        </table>
        <p v-if="shopeeItems.length > 3" class="more-note">
          ... +{{ shopeeItems.length - 3 }} lainnya
        </p>
      </div>

      <!-- TikTok Preview -->
      <div v-if="tiktokItems.length > 0" class="platform-preview">
        <h3 class="platform-title">
          <span class="platform-badge tiktok">TikTok</span>
          {{ tiktokItems.length }} item
        </h3>
        <table class="preview-table" aria-label="TikTok MPQ preview">
          <thead>
            <tr>
              <th scope="col">SKU</th>
              <th scope="col">Harga Awal</th>
              <th scope="col">Harga Baru</th>
              <th scope="col">MPQ</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in tiktokPreview" :key="item.sku">
              <td class="sku-cell">{{ item.sku }}</td>
              <td>{{ formatPrice(item.price) }}</td>
              <td class="price-cell">{{ formatPrice(item.newPrice) }}</td>
              <td>{{ selectedMinQty }}</td>
            </tr>
          </tbody>
        </table>
        <p v-if="tiktokItems.length > 3" class="more-note">
          ... +{{ tiktokItems.length - 3 }} lainnya
        </p>
      </div>
    </div>

    <div v-else class="no-items">Tidak ada item Shopee/TikTok yang dipilih</div>

    <!-- Action Buttons -->
    <div
      class="action-buttons"
      v-if="shopeeItems.length + tiktokItems.length > 0"
    >
      <button
        class="btn-update"
        @click="handleUpdate"
        :disabled="processing || localProcessing"
      >
        <span v-if="localProcessing" class="btn-loading">
          <span class="spinner"></span>
          Updating...
        </span>
        <span v-else>📦 Update MPQ</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { WholesaleSettings } from "../../../../services/wholesaleService";
import wholesaleService from "../../../../services/wholesaleService";

interface UpdateItem {
  sku: string;
  price: number;
  platform: string;
}

const props = defineProps<{
  shopeeItems: UpdateItem[];
  tiktokItems: UpdateItem[];
  settings: WholesaleSettings;
  processing: boolean;
}>();

const emit = defineEmits<{
  update: [result: any];
}>();

const selectedTier = ref<"normal" | "tier1" | "tier2" | "tier3">("tier1");
const localProcessing = ref(false);

const tiers = computed(() => [
  { value: "normal" as const, label: "Normal", minQty: 1 },
  {
    value: "tier1" as const,
    label: "Tier 1",
    minQty: props.settings.min_order_1,
  },
  {
    value: "tier2" as const,
    label: "Tier 2",
    minQty: props.settings.max_order_1 + 1,
  },
  {
    value: "tier3" as const,
    label: "Tier 3",
    minQty: props.settings.max_order_1 + 3,
  },
]);

const selectedMinQty = computed(() => {
  const tier = tiers.value.find((t) => t.value === selectedTier.value);
  return tier?.minQty || 1;
});

function calculateMpqPrice(originalPrice: number): number {
  if (selectedTier.value === "normal") return originalPrice;
  const tierCalc = wholesaleService.calculateTiersLocal(
    originalPrice,
    props.settings,
  );
  const tierIndex = { tier1: 0, tier2: 1, tier3: 2 }[selectedTier.value] ?? 0;
  return tierCalc[tierIndex]?.unit_price || originalPrice;
}

const shopeePreview = computed(() =>
  props.shopeeItems.slice(0, 3).map((item) => ({
    ...item,
    newPrice: calculateMpqPrice(item.price),
  })),
);

const tiktokPreview = computed(() =>
  props.tiktokItems.slice(0, 3).map((item) => ({
    ...item,
    newPrice: calculateMpqPrice(item.price),
  })),
);

function formatPrice(price: number): string {
  return new Intl.NumberFormat("id-ID").format(price);
}

async function handleUpdate() {
  if (localProcessing.value) return;
  localProcessing.value = true;
  const results: any[] = [];

  try {
    if (props.shopeeItems.length > 0) {
      // Map items with calculated newPrice based on selected tier
      const shopeeItemsWithPrice = props.shopeeItems.map((item) => ({
        sku: item.sku,
        price: calculateMpqPrice(item.price), // Use calculated tier price, not original
      }));

      const shopeeResult = await wholesaleService.batchShopeeMpq(
        shopeeItemsWithPrice,
        selectedMinQty.value,
      );
      // Extract failed SKUs from results array
      const failedSkus =
        shopeeResult.data?.results
          ?.filter((r: any) => !r.success)
          ?.map((r: any) => r.error || `Item ${r.item_id}`) || [];
      results.push({
        platform: "shopee",
        processed: shopeeResult.data?.processed || 0,
        failed: shopeeResult.data?.failed || 0,
        failedSkus,
      });
    }

    if (props.tiktokItems.length > 0) {
      // Map items with calculated newPrice based on selected tier
      const tiktokItemsWithPrice = props.tiktokItems.map((item) => ({
        sku: item.sku,
        price: calculateMpqPrice(item.price), // Use calculated tier price, not original
      }));

      const tiktokResult = await wholesaleService.batchTiktokMpq(
        tiktokItemsWithPrice,
        selectedMinQty.value,
      );
      // Extract failed from results array
      const failedSkus =
        tiktokResult.data?.results
          ?.filter((r: any) => !r.success)
          ?.map((r: any) => r.error || `Product ${r.product_id}`) || [];
      results.push({
        platform: "tiktok",
        processed: tiktokResult.data?.processed || 0,
        failed: tiktokResult.data?.failed || 0,
        failedSkus,
      });
    }

    const anyFailed = results.some((r) => r.failed > 0);
    emit("update", { success: !anyFailed, results });
  } catch (err: any) {
    emit("update", {
      success: false,
      message: err.message || "Gagal update MPQ",
    });
  } finally {
    localProcessing.value = false;
  }
}
</script>

<style src="./MpqTab.styles.css" scoped></style>

// frontend/src/pages/inventory/components/MpqTab.tsx
import { Alert, Button, Empty, message, Radio, Table, Typography } from "antd";
import { useEffect, useMemo, useState } from "react";
import {
  batchShopeeMpq,
  batchTiktokMpq,
  getSettings,
  type WholesaleSettings,
} from "@/api/wholesale";
import type { BulkPricingItem } from "../utils/bulkPricingItems";
import {
  DEFAULT_SETTINGS,
  formatCurrency,
  getAdjustedPrice,
  type PreviewRow,
  readCount,
  type TierKey,
} from "../utils/mpqTabHelpers";

interface MpqTabProps {
  items: BulkPricingItem[];
}

export function MpqTab({ items }: MpqTabProps) {
  const [settings, setSettings] = useState<WholesaleSettings>(DEFAULT_SETTINGS);
  const [loadingSettings, setLoadingSettings] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [selectedTier, setSelectedTier] = useState<TierKey>("tier1");
  const [resultMessage, setResultMessage] = useState<string | null>(null);
  const [resultType, setResultType] = useState<
    "success" | "warning" | "error" | null
  >(null);

  useEffect(() => {
    let cancelled = false;

    async function loadSettings() {
      setLoadingSettings(true);
      try {
        const loaded = await getSettings();
        if (!cancelled && loaded) {
          setSettings(loaded);
        }
      } catch (error) {
        if (!cancelled) {
          const rawMessage =
            error instanceof Error
              ? error.message
              : "Failed to load wholesale settings";
          message.error(rawMessage);
        }
      } finally {
        if (!cancelled) {
          setLoadingSettings(false);
        }
      }
    }

    void loadSettings();

    return () => {
      cancelled = true;
    };
  }, []);

  const shopeeItems = useMemo(() => {
    const unique = new Map<string, number>();
    for (const item of items) {
      if (item.platform !== "shopee") {
        continue;
      }
      if (!unique.has(item.sku)) {
        unique.set(item.sku, item.price);
      }
    }
    return Array.from(unique.entries()).map(([sku, price]) => ({ sku, price }));
  }, [items]);

  const tiktokItems = useMemo(() => {
    const unique = new Map<string, number>();
    for (const item of items) {
      if (item.platform !== "tiktok") {
        continue;
      }
      if (!unique.has(item.sku)) {
        unique.set(item.sku, item.price);
      }
    }
    return Array.from(unique.entries()).map(([sku, price]) => ({ sku, price }));
  }, [items]);

  const selectedMinQty = useMemo(() => {
    if (selectedTier === "normal") {
      return 1;
    }

    if (selectedTier === "tier1") {
      return settings.min_order_1;
    }

    if (selectedTier === "tier2") {
      return settings.max_order_1 + 1;
    }

    return settings.max_order_1 + 3;
  }, [selectedTier, settings.max_order_1, settings.min_order_1]);

  const previewRows = useMemo<PreviewRow[]>(() => {
    const shopeeRows = shopeeItems.slice(0, 3).map((item) => ({
      key: `shopee:${item.sku}`,
      platform: "Shopee",
      sku: item.sku,
      base_price: item.price,
      updated_price: getAdjustedPrice(item.price, settings, selectedTier),
      mpq: selectedMinQty,
    }));

    const tiktokRows = tiktokItems.slice(0, 3).map((item) => ({
      key: `tiktok:${item.sku}`,
      platform: "TikTok",
      sku: item.sku,
      base_price: item.price,
      updated_price: getAdjustedPrice(item.price, settings, selectedTier),
      mpq: selectedMinQty,
    }));

    return [...shopeeRows, ...tiktokRows];
  }, [selectedMinQty, selectedTier, settings, shopeeItems, tiktokItems]);

  const handleMpqUpdate = async () => {
    if (shopeeItems.length + tiktokItems.length === 0) {
      message.warning(
        "No Shopee or TikTok items available in current selection",
      );
      return;
    }

    setProcessing(true);
    setResultMessage(null);
    setResultType(null);

    let totalFailed = 0;
    const summaries: string[] = [];

    try {
      if (shopeeItems.length > 0) {
        const shopeePayload = shopeeItems.map((item) => ({
          sku: item.sku,
          price: getAdjustedPrice(item.price, settings, selectedTier),
        }));

        const shopeeResult = await batchShopeeMpq(
          shopeePayload,
          selectedMinQty,
        );
        const processed = readCount(shopeeResult.data, "processed");
        const failed = readCount(shopeeResult.data, "failed");
        totalFailed += failed;
        summaries.push(`Shopee ${processed} processed, ${failed} failed`);
      }

      if (tiktokItems.length > 0) {
        const tiktokPayload = tiktokItems.map((item) => ({
          sku: item.sku,
          price: getAdjustedPrice(item.price, settings, selectedTier),
        }));

        const tiktokResult = await batchTiktokMpq(
          tiktokPayload,
          selectedMinQty,
        );
        const processed = readCount(tiktokResult.data, "processed");
        const failed = readCount(tiktokResult.data, "failed");
        totalFailed += failed;
        summaries.push(`TikTok ${processed} processed, ${failed} failed`);
      }

      const summary = `MPQ update (min_qty=${selectedMinQty}): ${summaries.join(" | ")}`;
      setResultMessage(summary);

      if (totalFailed > 0) {
        setResultType("warning");
        message.warning(summary);
      } else {
        setResultType("success");
        message.success(summary);
      }
    } catch (error) {
      const rawMessage =
        error instanceof Error ? error.message : "Failed to update MPQ";
      setResultType("error");
      setResultMessage(rawMessage);
      message.error(rawMessage);
    } finally {
      setProcessing(false);
    }
  };

  const columns = [
    {
      title: "Platform",
      dataIndex: "platform",
      key: "platform",
    },
    {
      title: "SKU",
      dataIndex: "sku",
      key: "sku",
    },
    {
      title: "Base Price",
      dataIndex: "base_price",
      key: "base_price",
      render: (value: number) => formatCurrency(value),
    },
    {
      title: "Updated Price",
      dataIndex: "updated_price",
      key: "updated_price",
      render: (value: number) => formatCurrency(value),
    },
    {
      title: "MPQ",
      dataIndex: "mpq",
      key: "mpq",
    },
  ];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <Alert
        type="info"
        showIcon
        message={`Shopee ${shopeeItems.length} SKU, TikTok ${tiktokItems.length} SKU`}
        description="MPQ update sends calculated price + selected minimum quantity to each platform."
      />

      <div>
        <Typography.Text strong>Select tier target</Typography.Text>
        <Radio.Group
          style={{ display: "block", marginTop: 8 }}
          value={selectedTier}
          onChange={(event) => setSelectedTier(event.target.value as TierKey)}
          optionType="button"
          buttonStyle="solid"
          options={[
            { label: "Normal (1)", value: "normal" },
            {
              label: `Tier 1 (${settings.min_order_1})`,
              value: "tier1",
            },
            {
              label: `Tier 2 (${settings.max_order_1 + 1})`,
              value: "tier2",
            },
            {
              label: `Tier 3 (${settings.max_order_1 + 3})`,
              value: "tier3",
            },
          ]}
        />
      </div>

      {resultMessage && resultType ? (
        <Alert
          type={resultType}
          showIcon
          message={resultMessage}
          closable
          onClose={() => {
            setResultMessage(null);
            setResultType(null);
          }}
        />
      ) : null}

      <Button
        type="primary"
        loading={processing}
        onClick={handleMpqUpdate}
        disabled={shopeeItems.length + tiktokItems.length === 0}
      >
        Update MPQ
      </Button>

      <Table
        dataSource={previewRows}
        columns={columns}
        rowKey="key"
        loading={loadingSettings}
        pagination={false}
        locale={{
          emptyText: (
            <Empty description="No Shopee/TikTok items with valid price in current selection" />
          ),
        }}
      />
    </div>
  );
}
