// frontend/src/components/content/InventoryContent/InventoryColumnsModal.vue
<template>
  <div v-if="isOpen" class="modal-overlay" @click.self="close">
    <div class="modal-content">
      <div class="modal-header">
        <h3>⚙️ Inventory Column Configuration</h3>
        <button
          @click="close"
          class="btn-close"
          type="button"
          aria-label="Close modal"
        >
          ✕
        </button>
      </div>

      <div class="modal-body">
        <div v-if="loading" class="loading-state">
          <div class="spinner"></div>
          <span>Loading columns...</span>
        </div>

        <div v-else class="columns-config">
          <div class="info-text">
            <p>
              Select which columns from Google Sheets to display in the
              inventory table.
            </p>
            <p class="text-sm">
              Total: {{ availableColumns.length }} (A-{{
                getLastColumnLetter(availableColumns.length)
              }})
            </p>
          </div>

          <!-- Selected Columns -->
          <div v-if="selectedColumns.length > 0" class="selected-section">
            <h4>Selected ({{ selectedColumns.length }})</h4>
            <div class="selected-list">
              <div
                v-for="colName in selectedColumns"
                :key="colName"
                class="selected-item"
              >
                <span>{{ colName }}</span>
                <button @click="removeColumn(colName)" class="btn-remove">
                  ✕
                </button>
              </div>
            </div>
          </div>

          <!-- Available Columns -->
          <div class="available-section">
            <h4>
              Available
              <button @click="selectAll" class="btn-small">Select All</button>
              <button @click="clearAll" class="btn-small btn-secondary">
                Clear All
              </button>
            </h4>

            <div v-if="availableColumns.length === 0" class="empty-state">
              <p>No columns available. Configure spreadsheet first.</p>
            </div>

            <div v-else class="columns-grid">
              <ColumnCheckbox
                v-for="column in availableColumns"
                :key="column.name"
                :column="column"
                :is-selected="isSelected(column.name)"
                @toggle="toggleColumn(column.name)"
              />
            </div>
          </div>

          <div v-if="errorMessage" class="alert alert-error">
            {{ errorMessage }}
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button @click="close" class="btn btn-secondary">Cancel</button>
        <button
          @click="handleSave"
          :disabled="saving || loading"
          class="btn btn-primary"
        >
          {{ saving ? "Saving..." : "Save" }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { useColumnConfiguration } from "./composables/useColumnConfiguration";
import ColumnCheckbox from "./ColumnCheckbox.vue";

const props = defineProps<{ isOpen: boolean }>();
const emit = defineEmits<{ close: []; saved: [] }>();

const {
  loadAvailableColumns,
  loadSelectedColumns,
  saveColumnConfiguration,
  getLastColumnLetter,
} = useColumnConfiguration();

const loading = ref(false);
const saving = ref(false);
const availableColumns = ref<any[]>([]);
const selectedColumns = ref<string[]>([]);
const errorMessage = ref("");

watch(
  () => props.isOpen,
  async (newVal) => {
    if (newVal) {
      try {
        loading.value = true;
        errorMessage.value = "";
        const [available, selected] = await Promise.all([
          loadAvailableColumns(),
          loadSelectedColumns(),
        ]);
        availableColumns.value = available;
        selectedColumns.value = selected;
      } catch (error: any) {
        errorMessage.value = error.message;
      } finally {
        loading.value = false;
      }
    }
  }
);

function isSelected(columnName: string): boolean {
  return selectedColumns.value.includes(columnName);
}

function toggleColumn(columnName: string) {
  const index = selectedColumns.value.indexOf(columnName);
  if (index > -1) {
    selectedColumns.value.splice(index, 1);
  } else {
    selectedColumns.value.push(columnName);
  }
}

function removeColumn(columnName: string) {
  const index = selectedColumns.value.indexOf(columnName);
  if (index > -1) {
    selectedColumns.value.splice(index, 1);
  }
}

function selectAll() {
  selectedColumns.value = availableColumns.value.map((col) => col.name);
}

function clearAll() {
  selectedColumns.value = [];
}

async function handleSave() {
  try {
    saving.value = true;
    errorMessage.value = "";
    await saveColumnConfiguration(selectedColumns.value);
    emit("saved");
    close();
  } catch (error: any) {
    errorMessage.value = error.message;
  } finally {
    saving.value = false;
  }
}

function close() {
  emit("close");
}
</script>

<style scoped>
@import "./InventoryColumnsModal.styles.css";
</style>

// frontend/src/components/modals/InventoryColumnsModal.tsx
import {
  Modal,
  Button,
  Spin,
  Checkbox,
  message,
  Typography,
  Space,
} from "antd";
import { useState, useEffect } from "react";

const { Text } = Typography;

interface InventoryColumn {
  name: string;
  type: string;
}

interface InventoryColumnsModalProps {
  open: boolean;
  onClose: () => void;
}

export function InventoryColumnsModal({
  open,
  onClose,
}: InventoryColumnsModalProps) {
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [availableColumns, setAvailableColumns] = useState<InventoryColumn[]>(
    [],
  );
  const [selectedColumns, setSelectedColumns] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadColumns = async () => {
      setLoading(true);
      setError(null);
      try {
        // Mock data
        await new Promise((resolve) => setTimeout(resolve, 500));
        setAvailableColumns([
          { name: "Product Name", type: "string" },
          { name: "SKU", type: "string" },
          { name: "Stock", type: "number" },
          { name: "Price", type: "number" },
        ]);
        setSelectedColumns(["Product Name", "SKU", "Stock"]);
      } catch (err) {
        setError("Failed to load columns");
      } finally {
        setLoading(false);
      }
    };

    if (open) {
      loadColumns();
    }
  }, [open]);

  const handleSave = async () => {
    setSaving(true);
    try {
      await new Promise((resolve) => setTimeout(resolve, 500));
      message.success("Columns configuration saved");
      onClose();
    } catch (err) {
      message.error("Failed to save configuration");
    } finally {
      setSaving(false);
    }
  };

  const toggleColumn = (columnName: string) => {
    if (selectedColumns.includes(columnName)) {
      setSelectedColumns(selectedColumns.filter((c) => c !== columnName));
    } else {
      setSelectedColumns([...selectedColumns, columnName]);
    }
  };

  const selectAll = () => {
    setSelectedColumns(availableColumns.map((c) => c.name));
  };

  const clearAll = () => {
    setSelectedColumns([]);
  };

  return (
    <Modal
      title="⚙️ Inventory Column Configuration"
      open={open}
      onCancel={onClose}
      footer={[
        <Button key="cancel" onClick={onClose}>
          Cancel
        </Button>,
        <Button
          key="save"
          type="primary"
          onClick={handleSave}
          loading={saving}
          disabled={loading}
        >
          Save
        </Button>,
      ]}
      width={600}
    >
      {loading ? (
        <div style={{ textAlign: "center", padding: 24 }}>
          <Spin tip="Loading columns..." />
        </div>
      ) : error ? (
        <div style={{ color: "red", textAlign: "center" }}>{error}</div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Text type="secondary">
            Select which columns from Google Sheets to display in the inventory
            table. Total: {availableColumns.length}
          </Text>

          {/* Selected Columns */}
          {selectedColumns.length > 0 && (
            <div
              style={{
                background: "#f5f5f5",
                padding: 12,
                borderRadius: 6,
              }}
            >
              <Text strong>Selected ({selectedColumns.length})</Text>
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: 8,
                  marginTop: 8,
                }}
              >
                {selectedColumns.map((col) => (
                  <div
                    key={col}
                    style={{
                      background: "white",
                      padding: "4px 8px",
                      borderRadius: 4,
                      border: "1px solid #d9d9d9",
                      fontSize: 12,
                      display: "flex",
                      alignItems: "center",
                      gap: 4,
                    }}
                  >
                    {col}
                    <button
                      type="button"
                      style={{
                        cursor: "pointer",
                        color: "#999",
                        fontWeight: "bold",
                        background: "none",
                        border: "none",
                        padding: 0,
                        marginLeft: 4,
                      }}
                      onClick={() => toggleColumn(col)}
                      aria-label={`Remove ${col}`}
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Available Columns */}
          <div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginBottom: 8,
              }}
            >
              <Text strong>Available</Text>
              <Space>
                <Button size="small" onClick={selectAll}>
                  Select All
                </Button>
                <Button size="small" onClick={clearAll}>
                  Clear All
                </Button>
              </Space>
            </div>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
                gap: 8,
                maxHeight: 300,
                overflowY: "auto",
              }}
            >
              {availableColumns.map((col) => (
                <Checkbox
                  key={col.name}
                  checked={selectedColumns.includes(col.name)}
                  onChange={() => toggleColumn(col.name)}
                >
                  {col.name}
                </Checkbox>
              ))}
            </div>
          </div>
        </div>
      )}
    </Modal>
  );
}
